# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'sort_app.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(614, 530)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(250, 20, 131, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Black")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(200, 80, 221, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit.setFont(font)
        self.lineEdit.setObjectName("lineEdit")
        self.bubbleButton = QtWidgets.QPushButton(self.centralwidget)
        self.bubbleButton.setGeometry(QtCore.QRect(130, 120, 110, 45))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.bubbleButton.setFont(font)
        self.bubbleButton.setObjectName("bubbleButton")
        self.selectionButton = QtWidgets.QPushButton(self.centralwidget)
        self.selectionButton.setGeometry(QtCore.QRect(255, 120, 110, 45))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.selectionButton.setFont(font)
        self.selectionButton.setObjectName("selectionButton")
        self.insertionButton = QtWidgets.QPushButton(self.centralwidget)
        self.insertionButton.setGeometry(QtCore.QRect(380, 120, 110, 45))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.insertionButton.setFont(font)
        self.insertionButton.setObjectName("insertionButton")
        self.heapButton = QtWidgets.QPushButton(self.centralwidget)
        self.heapButton.setGeometry(QtCore.QRect(130, 170, 110, 45))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.heapButton.setFont(font)
        self.heapButton.setObjectName("heapButton")
        self.mergeButton = QtWidgets.QPushButton(self.centralwidget)
        self.mergeButton.setGeometry(QtCore.QRect(255, 170, 110, 45))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.mergeButton.setFont(font)
        self.mergeButton.setObjectName("mergeButton")
        self.quickButton = QtWidgets.QPushButton(self.centralwidget)
        self.quickButton.setGeometry(QtCore.QRect(380, 170, 110, 45))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.quickButton.setFont(font)
        self.quickButton.setObjectName("quickButton")
        self.clearButton = QtWidgets.QPushButton(self.centralwidget)
        self.clearButton.setGeometry(QtCore.QRect(230, 490, 181, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.clearButton.setFont(font)
        self.clearButton.setObjectName("clearButton")
        self.listWidget = QtWidgets.QListWidget(self.centralwidget)
        self.listWidget.setGeometry(QtCore.QRect(100, 230, 201, 251))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.listWidget.setFont(font)
        self.listWidget.setObjectName("listWidget")
        self.sortWidget = QtWidgets.QListWidget(self.centralwidget)
        self.sortWidget.setGeometry(QtCore.QRect(320, 230, 201, 251))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.sortWidget.setFont(font)
        self.sortWidget.setObjectName("sortWidget")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(105, 69, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(105, 90, 91, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.delButton = QtWidgets.QPushButton(self.centralwidget)
        self.delButton.setGeometry(QtCore.QRect(430, 80, 51, 31))
        self.delButton.setObjectName("delButton")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Ввод списка"))
        self.bubbleButton.setText(_translate("MainWindow", "Пузырьковая"))
        self.selectionButton.setText(_translate("MainWindow", "Выборкой"))
        self.insertionButton.setText(_translate("MainWindow", "Вставками"))
        self.heapButton.setText(_translate("MainWindow", "Пирамидальная"))
        self.mergeButton.setText(_translate("MainWindow", "Слиянием"))
        self.quickButton.setText(_translate("MainWindow", "Быстрая"))
        self.clearButton.setText(_translate("MainWindow", "Очистить список"))
        self.label_2.setText(_translate("MainWindow", "Пример ввода:"))
        self.label_3.setText(_translate("MainWindow", "4,6,0,7,1,9,7,2"))
        self.delButton.setText(_translate("MainWindow", "del"))
